### PR TITLE
Add new wavefront control system

### PR DESCRIPTION
**Pull request by PabloRdrRbl**
This PR implements a new WFS strategy in the observatory.

# Features

- [x] Add apodizer
- [x] Add DM on M4
- [ ] Add new software (de-scoped)

# Bug fixes

### CODE REVIEW

**Comment by PabloRdrRbl** [comment]
OK, so this is the way we implement DM at M4.

**Comment by ivalaginja** [comment]
Should the DM really go on M4 or maybe it's better on M3?

**Comment by PabloRdrRbl** [comment]
> Should the DM really go on M4 or maybe it's better on M3?

It's M4, like ELT.

**Comment by ivalaginja** [comment]
Ok cool, thanks for the clarification.

**Comment by PabloRdrRbl** [comment]
I will do the SW later. Is this fine?

**Pull request merged**
